
=head1 NAME

OODoc::Text::Diagnostic - one explanation of a problem report

=head1 INHERITANCE

 OODoc::Text::Diagnostic
   is a OODoc::Text
   is a OODoc::Object

=head1 SYNOPSIS


=head1 DESCRIPTION

Each OODoc::Text::Subroutine can have a list of warning and 
error messages, which are each captured in a separate object as described
in this manual page.

=head1 METHODS


$obj-E<gt>B<subroutine>

=over 4

Returns the subroutine object for this option.

=back

=head2 Attributes


$obj-E<gt>B<description>

=over 4

See L<OODoc::Text/"Attributes">

=back

$obj-E<gt>B<findDescriptionObject>

=over 4

See L<OODoc::Text/"Attributes">

=back

$obj-E<gt>B<openDescription>

=over 4

See L<OODoc::Text/"Attributes">

=back

$obj-E<gt>B<type>

=over 4

See L<OODoc::Text/"Attributes">

=back

$obj-E<gt>B<where>

=over 4

See L<OODoc::Text/"Attributes">

=back

=head2 Container


$obj-E<gt>B<container>

=over 4

See L<OODoc::Text/"Container">

=back

$obj-E<gt>B<manual>

=over 4

See L<OODoc::Text/"Container">

=back

=head2 Examples


$obj-E<gt>B<example>(OBJECT)

=over 4

See L<OODoc::Text/"Examples">

=back

$obj-E<gt>B<examples>

=over 4

See L<OODoc::Text/"Examples">

=back

=head2 Initiation


OODoc::Text::Diagnostic-E<gt>B<new>(OPTIONS)

=over 4

 Option            Defined in       Default     
 additional_rules  OODoc::Parser::Markov  []          
 chapter           OODoc::Text::Section  <required>  
 container         OODoc::Text      <subroutine>
 description       OODoc::Text      ''          
 filename          OODoc::Manifest  C<undef>    
 linenr            OODoc::Text      <required>  
 manual            OODoc::Text::Chapter  <required>  
 module            OODoc            <required>  
 name              OODoc::Text      C<undef>    
 package           OODoc::Manual    <required>  
 parameters        OODoc::Text::Subroutine  C<undef>    
 parser            OODoc::Manual    <required>  
 pure_pod          OODoc::Manual    0           
 section           OODoc::Text::SubSection  <required>  
 source            OODoc::Manual    <required>  
 stripped          OODoc::Manual    C<undef>    
 subroutine                         <required>  
 type              OODoc::Text      <required>  
 value             OODoc::Text::Default  <required>  
 verbose           OODoc            0           
 version           OODoc            <required>  
 workdir           OODoc            C<undef>    

. additional_rules ARRAY

. chapter OBJECT

. container OBJECT

. description STRING

. filename FILENAME

. linenr INTEGER

. manual OBJECT

. module STRING

. name STRING

. package STRING

. parameters STRING

. parser OBJECT

. pure_pod BOOLEAN

. section OBJECT

. source STRING

. stripped STRING

. subroutine OBJECT

=over 4

The subroutine in which this option lives.

=back

. type STRING

. value STRING

. verbose INTEGER

. version STRING

. workdir DIRECTORY

=back

=head2 Inheritance


$obj-E<gt>B<extends>([OBJECT])

=over 4

See L<OODoc::Object/"Inheritance">

=back

=head2 Commonly used functions


$obj-E<gt>B<filenameToPackage>(FILENAME)

OODoc::Text::Diagnostic-E<gt>B<filenameToPackage>(FILENAME)

=over 4

See L<OODoc::Object/"Commonly used functions">

=back

$obj-E<gt>B<mergeObjects>(OPTIONS)

=over 4

See L<OODoc::Object/"Commonly used functions">

=back

$obj-E<gt>B<mkdirhier>(DIRECTORY)

OODoc::Text::Diagnostic-E<gt>B<mkdirhier>(DIRECTORY)

=over 4

See L<OODoc::Object/"Commonly used functions">

=back

$obj-E<gt>B<unique>

=over 4

See L<OODoc::Text/"METHODS">

=back

=head2 Manual database

All manuals can be reached everywhere in the program: it is a global
collection.

$obj-E<gt>B<addManual>(MANUAL)

=over 4

See L<OODoc::Object/"Manual database">

=back

$obj-E<gt>B<mainManual>(NAME)

=over 4

See L<OODoc::Object/"Manual database">

=back

$obj-E<gt>B<manuals>

=over 4

See L<OODoc::Object/"Manual database">

=back

$obj-E<gt>B<manualsForPackage>(NAME)

=over 4

See L<OODoc::Object/"Manual database">

=back

$obj-E<gt>B<packageNames>

=over 4

See L<OODoc::Object/"Manual database">

=back

=head1 DIAGNOSTICS

I<Error:> manual definition requires manual object

A call to L<addManual()|OODoc::Object/"Manual database"> expects a new manual object (a L<OODoc::Manual|OODoc::Manual>),
however an incompatible thing was passed.  Usually, intended was a call
to L<manualsForPackage()|OODoc::Object/"Manual database"> or L<mainManual()|OODoc::Object/"Manual database">.

I<Warning:> order conflict "$take" before "$insert" in $file line $number

The order of the objects in a sub-class shall be the same as that of
the super class, otherwise the result of merging of the information
received from both classes is undertermined.

=head2 COPYRIGHTS

all mine.

